name: CI

on:
  push:
    branches-ignore: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: 17

    - name: Build
      run: gradle

    - name: Test
      run: gradle test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libs-output
        path: build/libs/*
